
/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */
#ifndef HIJACK_CUDA_HELPER_H
#define HIJACK_CUDA_HELPER_H
#ifdef __cplusplus
extern "C" {

#endif

/**
 *  CUDA library prefix
 */
#define CUDA_ENTRY_ENUM(x) ENTRY_##x
#define CUDA_FIND_ENTRY(table, sym) ({ (table)[CUDA_ENTRY_ENUM(sym)]; })

/**
 * CUDA library function pointer
 */
#define CUDA_ENTRY_CALL(table, sym, ...)                            \
    ({                                                              \
        int (*hookFunc)() = (int (*)())CUDA_FIND_ENTRY(table, sym); \
        hookFunc(__VA_ARGS__);                                      \
    })

/**
 * CUDA library enumerator entry
 */
typedef enum {
    CUDA_ENTRY_ENUM(cuInit),
    CUDA_ENTRY_ENUM(cudbgMain),
    CUDA_ENTRY_ENUM(cudbgGetAPIVersion),
    CUDA_ENTRY_ENUM(cuArray3DGetDescriptor_v2),
    CUDA_ENTRY_ENUM(cudbgGetAPI),
    CUDA_ENTRY_ENUM(cuGetProcAddress_v2_alt),
    CUDA_ENTRY_ENUM(cuMemAddressFree),
    CUDA_ENTRY_ENUM(cuMemRelease),
    CUDA_ENTRY_ENUM(cuMemoryAllocate),
    CUDA_ENTRY_ENUM(cuDeviceGetAttribute),
    CUDA_ENTRY_ENUM(cuMemUnmap),
    CUDA_ENTRY_ENUM(cuMemoryFree),
    CUDA_ENTRY_ENUM(cuUnmapMemory),
    CUDA_ENTRY_ENUM(cuMemSetAccess),
    CUDA_ENTRY_ENUM(cuDeviceGet),
    CUDA_ENTRY_ENUM(cuDeviceGetCount),
    CUDA_ENTRY_ENUM(cuDeviceGetName),
    CUDA_ENTRY_ENUM(cuDeviceCanAccessPeer),
    CUDA_ENTRY_ENUM(cuDeviceGetP2PAttribute),
    CUDA_ENTRY_ENUM(cuDeviceGetByPCIBusId),
    CUDA_ENTRY_ENUM(cuDeviceGetPCIBusId),
    CUDA_ENTRY_ENUM(cuDeviceGetUuid),
    CUDA_ENTRY_ENUM(cuDeviceGetDefaultMemPool),
    CUDA_ENTRY_ENUM(cuDeviceGetLuid),
    CUDA_ENTRY_ENUM(cuDeviceGetMemPool),
    CUDA_ENTRY_ENUM(cuDeviceTotalMem_v2),
    CUDA_ENTRY_ENUM(cuDriverGetVersion),
    CUDA_ENTRY_ENUM(cuDeviceGetTexture1DLinearMaxWidth),
    CUDA_ENTRY_ENUM(cuDeviceSetMemPool),
    CUDA_ENTRY_ENUM(cuFlushGPUDirectRDMAWrites),
    CUDA_ENTRY_ENUM(cuDevicePrimaryCtxGetState),
    CUDA_ENTRY_ENUM(cuDevicePrimaryCtxRetain),
    CUDA_ENTRY_ENUM(cuDevicePrimaryCtxSetFlags_v2),
    CUDA_ENTRY_ENUM(cuDevicePrimaryCtxRelease),
    CUDA_ENTRY_ENUM(cuDevicePrimaryCtxRelease_v2),
    CUDA_ENTRY_ENUM(cuCtxGetDevice),
    CUDA_ENTRY_ENUM(cuCtxCreate_v2),
    CUDA_ENTRY_ENUM(cuCtxDestroy_v2),
    CUDA_ENTRY_ENUM(cuCtxGetApiVersion),
    CUDA_ENTRY_ENUM(cuCtxGetCacheConfig),
    CUDA_ENTRY_ENUM(cuCtxGetCurrent),
    CUDA_ENTRY_ENUM(cuCtxGetFlags),
    CUDA_ENTRY_ENUM(cuCtxGetLimit),
    CUDA_ENTRY_ENUM(cuCtxGetSharedMemConfig),
    CUDA_ENTRY_ENUM(cuCtxGetStreamPriorityRange),
    CUDA_ENTRY_ENUM(cuCtxPopCurrent),
    CUDA_ENTRY_ENUM(cuCtxPopCurrent_v2),
    CUDA_ENTRY_ENUM(cuCtxPushCurrent),
    CUDA_ENTRY_ENUM(cuCtxPushCurrent_v2),
    CUDA_ENTRY_ENUM(cuCtxSetCacheConfig),
    CUDA_ENTRY_ENUM(cuCtxSetCurrent),
    CUDA_ENTRY_ENUM(cuCtxSetLimit),
    CUDA_ENTRY_ENUM(cuCtxSetSharedMemConfig),
    CUDA_ENTRY_ENUM(cuCtxSynchronize),
    CUDA_ENTRY_ENUM(cuGetExportTable),
    CUDA_ENTRY_ENUM(cuStreamCreate),
    CUDA_ENTRY_ENUM(cuStreamDestroy_v2),
    CUDA_ENTRY_ENUM(cuStreamSynchronize),
    CUDA_ENTRY_ENUM(cuArray3DCreate_v2),
    CUDA_ENTRY_ENUM(cuArrayCreate_v2),
    CUDA_ENTRY_ENUM(cuArrayDestroy),
    CUDA_ENTRY_ENUM(cuMemAlloc_v2),
    CUDA_ENTRY_ENUM(cuMemAllocHost_v2),
    CUDA_ENTRY_ENUM(cuMemAllocManaged),
    CUDA_ENTRY_ENUM(cuMemAllocPitch_v2),
    CUDA_ENTRY_ENUM(cuMemFree_v2),
    CUDA_ENTRY_ENUM(cuMemFreeHost),
    CUDA_ENTRY_ENUM(cuMemHostAlloc),
    CUDA_ENTRY_ENUM(cuMemHostRegister_v2),
    CUDA_ENTRY_ENUM(cuMemHostUnregister),
    CUDA_ENTRY_ENUM(cuMemcpyDtoH_v2),
    CUDA_ENTRY_ENUM(cuMemcpyHtoD_v2),
    CUDA_ENTRY_ENUM(cuMipmappedArrayCreate),
    CUDA_ENTRY_ENUM(cuMipmappedArrayDestroy),
    CUDA_ENTRY_ENUM(cuMemGetInfo_v2),
    CUDA_ENTRY_ENUM(cuMemcpy),
    CUDA_ENTRY_ENUM(cuPointerGetAttribute),
    CUDA_ENTRY_ENUM(cuPointerGetAttributes),
    CUDA_ENTRY_ENUM(cuPointerSetAttribute),
    CUDA_ENTRY_ENUM(cuIpcCloseMemHandle),
    CUDA_ENTRY_ENUM(cuIpcGetMemHandle),
    CUDA_ENTRY_ENUM(cuIpcOpenMemHandle_v2),
    CUDA_ENTRY_ENUM(cuMemGetAddressRange_v2),
    CUDA_ENTRY_ENUM(cuMemcpyAsync),
    CUDA_ENTRY_ENUM(cuMemcpyAtoD_v2),
    CUDA_ENTRY_ENUM(cuMemcpyDtoA_v2),
    CUDA_ENTRY_ENUM(cuMemcpyDtoD_v2),
    CUDA_ENTRY_ENUM(cuMemcpyDtoDAsync_v2),
    CUDA_ENTRY_ENUM(cuMemcpyDtoHAsync_v2),
    CUDA_ENTRY_ENUM(cuMemcpyHtoDAsync_v2),
    CUDA_ENTRY_ENUM(cuMemcpyPeer),
    CUDA_ENTRY_ENUM(cuMemcpyPeerAsync),
    CUDA_ENTRY_ENUM(cuMemsetD16_v2),
    CUDA_ENTRY_ENUM(cuMemsetD16Async),
    CUDA_ENTRY_ENUM(cuMemsetD2D16_v2),
    CUDA_ENTRY_ENUM(cuMemsetD2D16Async),
    CUDA_ENTRY_ENUM(cuMemsetD2D32_v2),
    CUDA_ENTRY_ENUM(cuMemsetD2D32Async),
    CUDA_ENTRY_ENUM(cuMemsetD2D8_v2),
    CUDA_ENTRY_ENUM(cuMemsetD2D8Async),
    CUDA_ENTRY_ENUM(cuMemsetD32_v2),
    CUDA_ENTRY_ENUM(cuMemsetD32Async),
    CUDA_ENTRY_ENUM(cuMemsetD8_v2),
    CUDA_ENTRY_ENUM(cuMemsetD8Async),
    CUDA_ENTRY_ENUM(cuMemAdvise),
    CUDA_ENTRY_ENUM(cuFuncSetCacheConfig),
    CUDA_ENTRY_ENUM(cuFuncSetSharedMemConfig),
    CUDA_ENTRY_ENUM(cuFuncGetAttribute),
    CUDA_ENTRY_ENUM(cuFuncSetAttribute),
    CUDA_ENTRY_ENUM(cuLaunchKernel),
    CUDA_ENTRY_ENUM(cuLaunchCooperativeKernel),
    CUDA_ENTRY_ENUM(cuEventCreate),
    CUDA_ENTRY_ENUM(cuEventDestroy_v2),
    CUDA_ENTRY_ENUM(cuModuleLoad),
    CUDA_ENTRY_ENUM(cuModuleLoadData),
    CUDA_ENTRY_ENUM(cuModuleLoadDataEx),
    CUDA_ENTRY_ENUM(cuModuleLoadFatBinary),
    CUDA_ENTRY_ENUM(cuModuleGetFunction),
    CUDA_ENTRY_ENUM(cuModuleUnload),
    CUDA_ENTRY_ENUM(cuModuleGetGlobal_v2),
    CUDA_ENTRY_ENUM(cuModuleGetTexRef),
    CUDA_ENTRY_ENUM(cuModuleGetSurfRef),
    CUDA_ENTRY_ENUM(cuLinkAddData_v2),
    CUDA_ENTRY_ENUM(cuLinkCreate_v2),
    CUDA_ENTRY_ENUM(cuLinkAddFile_v2),
    CUDA_ENTRY_ENUM(cuLinkComplete),
    CUDA_ENTRY_ENUM(cuLinkDestroy),
    CUDA_ENTRY_ENUM(cuMemAddressReserve),
    CUDA_ENTRY_ENUM(cuMemCreate),
    CUDA_ENTRY_ENUM(cuMemMap),
    CUDA_ENTRY_ENUM(cuMemAllocAsync),
    CUDA_ENTRY_ENUM(cuMemHostGetDevicePointer_v2),
    CUDA_ENTRY_ENUM(cuMemHostGetFlags),
    CUDA_ENTRY_ENUM(cuMemPoolTrimTo),
    CUDA_ENTRY_ENUM(cuMemPoolSetAttribute),
    CUDA_ENTRY_ENUM(cuMemPoolGetAttribute),
    CUDA_ENTRY_ENUM(cuMemPoolSetAccess),
    CUDA_ENTRY_ENUM(cuMemPoolGetAccess),
    CUDA_ENTRY_ENUM(cuMemPoolCreate),
    CUDA_ENTRY_ENUM(cuMemPoolDestroy),
    CUDA_ENTRY_ENUM(cuMemAllocFromPoolAsync),
    CUDA_ENTRY_ENUM(cuMemPoolExportToShareableHandle),
    CUDA_ENTRY_ENUM(cuMemPoolImportFromShareableHandle),
    CUDA_ENTRY_ENUM(cuMemPoolExportPointer),
    CUDA_ENTRY_ENUM(cuMemPoolImportPointer),
    CUDA_ENTRY_ENUM(cuMemcpy2DUnaligned_v2),
    CUDA_ENTRY_ENUM(cuMemcpy2DAsync_v2),
    CUDA_ENTRY_ENUM(cuMemcpy3D_v2),
    CUDA_ENTRY_ENUM(cuMemcpy3DAsync_v2),
    CUDA_ENTRY_ENUM(cuMemcpy3DPeer),
    CUDA_ENTRY_ENUM(cuMemcpy3DPeerAsync),
    CUDA_ENTRY_ENUM(cuMemPrefetchAsync),
    CUDA_ENTRY_ENUM(cuMemRangeGetAttribute),
    CUDA_ENTRY_ENUM(cuMemRangeGetAttributes),
    CUDA_ENTRY_ENUM(cuImportExternalMemory),
    CUDA_ENTRY_ENUM(cuExternalMemoryGetMappedBuffer),
    CUDA_ENTRY_ENUM(cuExternalMemoryGetMappedMipmappedArray),
    CUDA_ENTRY_ENUM(cuDestroyExternalMemory),
    CUDA_ENTRY_ENUM(cuImportExternalSemaphore),
    CUDA_ENTRY_ENUM(cuSignalExternalSemaphoresAsync),
    CUDA_ENTRY_ENUM(cuWaitExternalSemaphoresAsync),
    CUDA_ENTRY_ENUM(cuDestroyExternalSemaphore),
    CUDA_ENTRY_ENUM(cuGraphCreate),
    CUDA_ENTRY_ENUM(cuGraphAddKernelNode_v2),
    CUDA_ENTRY_ENUM(cuGraphKernelNodeGetParams_v2),
    CUDA_ENTRY_ENUM(cuGraphKernelNodeSetParams_v2),
    CUDA_ENTRY_ENUM(cuGraphAddMemcpyNode),
    CUDA_ENTRY_ENUM(cuGraphMemcpyNodeGetParams),
    CUDA_ENTRY_ENUM(cuGraphMemcpyNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphAddMemsetNode),
    CUDA_ENTRY_ENUM(cuGraphMemsetNodeGetParams),
    CUDA_ENTRY_ENUM(cuGraphMemsetNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphAddHostNode),
    CUDA_ENTRY_ENUM(cuGraphHostNodeGetParams),
    CUDA_ENTRY_ENUM(cuGraphHostNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphAddChildGraphNode),
    CUDA_ENTRY_ENUM(cuGraphChildGraphNodeGetGraph),
    CUDA_ENTRY_ENUM(cuGraphAddEmptyNode),
    CUDA_ENTRY_ENUM(cuGraphAddEventRecordNode),
    CUDA_ENTRY_ENUM(cuGraphEventRecordNodeGetEvent),
    CUDA_ENTRY_ENUM(cuGraphEventRecordNodeSetEvent),
    CUDA_ENTRY_ENUM(cuGraphAddEventWaitNode),
    CUDA_ENTRY_ENUM(cuGraphEventWaitNodeGetEvent),
    CUDA_ENTRY_ENUM(cuGraphEventWaitNodeSetEvent),
    CUDA_ENTRY_ENUM(cuGraphAddExternalSemaphoresSignalNode),
    CUDA_ENTRY_ENUM(cuGraphExternalSemaphoresSignalNodeGetParams),
    CUDA_ENTRY_ENUM(cuGraphExternalSemaphoresSignalNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphAddExternalSemaphoresWaitNode),
    CUDA_ENTRY_ENUM(cuGraphExternalSemaphoresWaitNodeGetParams),
    CUDA_ENTRY_ENUM(cuGraphExternalSemaphoresWaitNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphExecExternalSemaphoresSignalNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphExecExternalSemaphoresWaitNodeSetParams),
    CUDA_ENTRY_ENUM(cuGraphClone),
    CUDA_ENTRY_ENUM(cuGraphNodeFindInClone),
    CUDA_ENTRY_ENUM(cuGraphNodeGetType),
    CUDA_ENTRY_ENUM(cuGraphGetNodes),
    CUDA_ENTRY_ENUM(cuGraphGetRootNodes),
    CUDA_ENTRY_ENUM(cuGraphGetEdges),
    CUDA_ENTRY_ENUM(cuGraphNodeGetDependencies),
    CUDA_ENTRY_ENUM(cuGraphNodeGetDependentNodes),
    CUDA_ENTRY_ENUM(cuGraphAddDependencies),
    CUDA_ENTRY_ENUM(cuGraphRemoveDependencies),
    CUDA_ENTRY_ENUM(cuGraphDestroyNode),
    CUDA_ENTRY_ENUM(cuGraphInstantiate),
    CUDA_ENTRY_ENUM(cuGraphInstantiateWithFlags),
    CUDA_ENTRY_ENUM(cuGraphUpload),
    CUDA_ENTRY_ENUM(cuGraphLaunch),
    CUDA_ENTRY_ENUM(cuGraphExecDestroy),
    CUDA_ENTRY_ENUM(cuGraphDestroy),
    CUDA_ENTRY_ENUM(cuGetProcAddress),
    CUDA_ENTRY_ENUM(cuGetProcAddress_v2),
    CUDA_ENTRY_ENUM(cuGetErrorString),
    CUDA_ENTRY_ENUM(cuMemGetAllocationGranularity),
    CUDA_ENTRY_ENUM(cuModuleGetLoadingMode),
    CUDA_ENTRY_ENUM(cuEventRecordWithFlags),
    CUDA_ENTRY_ENUM(cuGetErrorName),
    CUDA_ENTRY_ENUM(cuOccupancyMaxActiveBlocksPerMultiprocessor),
    CUDA_ENTRY_ENUM(cuDevicePrimaryCtxReset),
    CUDA_ENTRY_ENUM(cuLaunchKernelEx),
    CUDA_ENTRY_END
} cuda_entry_enum_t;

#ifdef __cplusplus
}
#endif
#endif // HIJACK_CUDA_HELPER_H