#include "cuda-subset.h"
 CUresult  cuCtxAttach ( CUcontext * pctx , unsigned int flags ) ;
 CUresult  cuCtxDetach ( CUcontext ctx ) ;
 CUresult  cuDeviceComputeCapability ( int * major , int * minor , CUdevice dev ) ;
 CUresult  cuDeviceGetProperties ( CUdevprop * prop , CUdevice dev ) ;
 CUresult  cuFuncSetBlockShape ( CUfunction hfunc , int x , int y , int z ) ;
 CUresult  cuFuncSetSharedSize ( CUfunction hfunc , unsigned int bytes ) ;
 CUresult  cuLaunch ( CUfunction f ) ;
 CUresult  cuLaunchCooperativeKernelMultiDevice ( CUDA_LAUNCH_PARAMS * launchParamsList , unsigned int numDevices , unsigned int flags ) ;
 CUresult  cuLaunchGrid ( CUfunction f , int grid_width , int grid_height ) ;
 CUresult  cuLaunchGridAsync ( CUfunction f , int grid_width , int grid_height , CUstream hStream ) ;
 CUresult  cuParamSetSize ( CUfunction hfunc , unsigned int numbytes ) ;
 CUresult  cuParamSetTexRef ( CUfunction hfunc , int texunit , CUtexref hTexRef ) ;
 CUresult  cuParamSetf ( CUfunction hfunc , int vgpu_offset , float value ) ;
 CUresult  cuParamSeti ( CUfunction hfunc , int vgpu_offset , unsigned int value ) ;
 CUresult  cuParamSetv ( CUfunction hfunc , int vgpu_offset , void * ptr , unsigned int numbytes ) ;
 CUresult  cuSurfRefGetArray ( CUarray * phArray , CUsurfref hSurfRef ) ;
 CUresult  cuSurfRefSetArray ( CUsurfref hSurfRef , CUarray hArray , unsigned int Flags ) ;
 CUresult  cuTexRefCreate ( CUtexref * pTexRef ) ;
 CUresult  cuTexRefDestroy ( CUtexref hTexRef ) ;
 CUresult  cuTexRefGetAddress ( CUdeviceptr * pdptr , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetAddressMode ( CUaddress_mode * pam , CUtexref hTexRef , int dim ) ;
 CUresult  cuTexRefGetArray ( CUarray * phArray , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetBorderColor ( float * pBorderColor , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetFilterMode ( CUfilter_mode * pfm , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetFlags ( unsigned int * pFlags , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetFormat ( CUarray_format * pFormat , int * pNumChannels , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetMaxAnisotropy ( int * pmaxAniso , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetMipmapFilterMode ( CUfilter_mode * pfm , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetMipmapLevelBias ( float * pbias , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetMipmapLevelClamp ( float * pminMipmapLevelClamp , float * pmaxMipmapLevelClamp , CUtexref hTexRef ) ;
 CUresult  cuTexRefGetMipmappedArray ( CUmipmappedArray * phMipmappedArray , CUtexref hTexRef ) ;
 CUresult  cuTexRefSetAddress ( size_t * ByteOffset , CUtexref hTexRef , CUdeviceptr dptr , size_t bytes ) ;
 CUresult  cuTexRefSetAddress2D ( CUtexref hTexRef , const CUDA_ARRAY_DESCRIPTOR * desc , CUdeviceptr dptr , size_t Pitch ) ;
 CUresult  cuTexRefSetAddressMode ( CUtexref hTexRef , int dim , CUaddress_mode am ) ;
 CUresult  cuTexRefSetArray ( CUtexref hTexRef , CUarray hArray , unsigned int Flags ) ;
 CUresult  cuTexRefSetBorderColor ( CUtexref hTexRef , float * pBorderColor ) ;
 CUresult  cuTexRefSetFilterMode ( CUtexref hTexRef , CUfilter_mode fm ) ;
 CUresult  cuTexRefSetFlags ( CUtexref hTexRef , unsigned int Flags ) ;
 CUresult  cuTexRefSetFormat ( CUtexref hTexRef , CUarray_format fmt , int NumPackedComponents ) ;
 CUresult  cuTexRefSetMaxAnisotropy ( CUtexref hTexRef , unsigned int maxAniso ) ;
 CUresult  cuTexRefSetMipmapFilterMode ( CUtexref hTexRef , CUfilter_mode fm ) ;
 CUresult  cuTexRefSetMipmapLevelBias ( CUtexref hTexRef , float bias ) ;
 CUresult  cuTexRefSetMipmapLevelClamp ( CUtexref hTexRef , float minMipmapLevelClamp , float maxMipmapLevelClamp ) ;
 CUresult  cuTexRefSetMipmappedArray ( CUtexref hTexRef , CUmipmappedArray hMipmappedArray , unsigned int Flags ) ;
CUresult  cuArray3DCreate ( CUarray * pHandle , const CUDA_ARRAY3D_DESCRIPTOR * pAllocateArray ) ;
CUresult  cuArray3DGetDescriptor ( CUDA_ARRAY3D_DESCRIPTOR * pArrayDescriptor , CUarray hArray ) ;
CUresult  cuArrayCreate ( CUarray * pHandle , const CUDA_ARRAY_DESCRIPTOR * pAllocateArray ) ;
CUresult  cuArrayDestroy ( CUarray hArray ) ;
CUresult  cuArrayGetDescriptor ( CUDA_ARRAY_DESCRIPTOR * pArrayDescriptor , CUarray hArray ) ;
CUresult  cuArrayGetPlane ( CUarray * pPlaneArray , CUarray hArray , unsigned int planeIdx ) ;
CUresult  cuArrayGetSparseProperties ( CUDA_ARRAY_SPARSE_PROPERTIES * sparseProperties , CUarray array ) ;
CUresult  cuCtxCreate ( CUcontext * pctx , unsigned int flags , CUdevice dev ) ;
CUresult  cuCtxCreate_v3 ( CUcontext * pctx , CUexecAffinityParam * paramsArray , int numParams , unsigned int flags , CUdevice dev ) ;
CUresult  cuCtxDestroy ( CUcontext ctx ) ;
CUresult  cuCtxDisablePeerAccess ( CUcontext peerContext ) ;
CUresult  cuCtxEnablePeerAccess ( CUcontext peerContext , unsigned int Flags ) ;
CUresult  cuCtxGetApiVersion ( CUcontext ctx , unsigned int * version ) ;
CUresult  cuCtxGetCacheConfig ( CUfunc_cache * pconfig ) ;
CUresult  cuCtxGetCurrent ( CUcontext * pctx ) ;
CUresult  cuCtxGetDevice ( CUdevice * device ) ;
CUresult  cuCtxGetExecAffinity ( CUexecAffinityParam * pExecAffinity , CUexecAffinityType type ) ;
CUresult  cuCtxGetFlags ( unsigned int * flags ) ;
CUresult  cuCtxGetLimit ( size_t * pvalue , CUlimit limit ) ;
CUresult  cuCtxGetSharedMemConfig ( CUsharedconfig * pConfig ) ;
CUresult  cuCtxGetStreamPriorityRange ( int * leastPriority , int * greatestPriority ) ;
CUresult  cuCtxPopCurrent ( CUcontext * pctx ) ;
CUresult  cuCtxPushCurrent ( CUcontext ctx ) ;
CUresult  cuCtxResetPersistingL2Cache ( void ) ;
CUresult  cuCtxSetCacheConfig ( CUfunc_cache config ) ;
CUresult  cuCtxSetCurrent ( CUcontext ctx ) ;
CUresult  cuCtxSetLimit ( CUlimit limit , size_t value ) ;
CUresult  cuCtxSetSharedMemConfig ( CUsharedconfig config ) ;
CUresult  cuCtxSynchronize ( void ) ;
CUresult  cuDestroyExternalMemory ( CUexternalMemory extMem ) ;
CUresult  cuDestroyExternalSemaphore ( CUexternalSemaphore extSem ) ;
CUresult  cuDeviceCanAccessPeer ( int * canAccessPeer , CUdevice dev , CUdevice peerDev ) ;
CUresult  cuDeviceGet ( CUdevice * device , int ordinal ) ;
CUresult  cuDeviceGetAttribute ( int * pi , CUdevice_attribute attrib , CUdevice dev ) ;
CUresult  cuDeviceGetByPCIBusId ( CUdevice * dev , const char * pciBusId ) ;
CUresult  cuDeviceGetCount ( int * count ) ;
CUresult  cuDeviceGetDefaultMemPool ( CUmemoryPool * pool_out , CUdevice dev ) ;
CUresult  cuDeviceGetExecAffinitySupport ( int * pi , CUexecAffinityType type , CUdevice dev ) ;
CUresult  cuDeviceGetGraphMemAttribute ( CUdevice device , CUgraphMem_attribute attr , void * value ) ;
CUresult  cuDeviceGetLuid ( char * luid , unsigned int * deviceNodeMask , CUdevice dev ) ;
CUresult  cuDeviceGetMemPool ( CUmemoryPool * pool , CUdevice dev ) ;
CUresult  cuDeviceGetName ( char * name , int len , CUdevice dev ) ;
CUresult  cuDeviceGetNvSciSyncAttributes ( void * nvSciSyncAttrList , CUdevice dev , int flags ) ;
CUresult  cuDeviceGetP2PAttribute ( int * value , CUdevice_P2PAttribute attrib , CUdevice srcDevice , CUdevice dstDevice ) ;
CUresult  cuDeviceGetPCIBusId ( char * pciBusId , int len , CUdevice dev ) ;
CUresult  cuDeviceGetTexture1DLinearMaxWidth ( size_t * maxWidthInElements , CUarray_format format , unsigned numChannels , CUdevice dev ) ;
CUresult  cuDeviceGetUuid ( CUuuid * uuid , CUdevice dev ) ;
CUresult  cuDeviceGetUuid_v2 ( CUuuid * uuid , CUdevice dev ) ;
CUresult  cuDeviceGraphMemTrim ( CUdevice device ) ;
CUresult  cuDevicePrimaryCtxGetState ( CUdevice dev , unsigned int * flags , int * active ) ;
CUresult  cuDevicePrimaryCtxRelease ( CUdevice dev ) ;
CUresult  cuDevicePrimaryCtxReset ( CUdevice dev ) ;
CUresult  cuDevicePrimaryCtxRetain ( CUcontext * pctx , CUdevice dev ) ;
CUresult  cuDevicePrimaryCtxSetFlags ( CUdevice dev , unsigned int flags ) ;
CUresult  cuDeviceSetGraphMemAttribute ( CUdevice device , CUgraphMem_attribute attr , void * value ) ;
CUresult  cuDeviceSetMemPool ( CUdevice dev , CUmemoryPool pool ) ;
CUresult  cuDeviceTotalMem ( size_t * bytes , CUdevice dev ) ;
CUresult  cuDriverGetVersion ( int * driverVersion ) ;
CUresult  cuEventCreate ( CUevent * phEvent , unsigned int Flags ) ;
CUresult  cuEventDestroy ( CUevent hEvent ) ;
CUresult  cuEventElapsedTime ( float * pMilliseconds , CUevent hStart , CUevent hEnd ) ;
CUresult  cuEventQuery ( CUevent hEvent ) ;
CUresult  cuEventRecord ( CUevent hEvent , CUstream hStream ) ;
CUresult  cuEventRecordWithFlags ( CUevent hEvent , CUstream hStream , unsigned int flags ) ;
CUresult  cuEventSynchronize ( CUevent hEvent ) ;
CUresult  cuExternalMemoryGetMappedBuffer ( CUdeviceptr * devPtr , CUexternalMemory extMem , const CUDA_EXTERNAL_MEMORY_BUFFER_DESC * bufferDesc ) ;
CUresult  cuExternalMemoryGetMappedMipmappedArray ( CUmipmappedArray * mipmap , CUexternalMemory extMem , const CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC * mipmapDesc ) ;
CUresult  cuFlushGPUDirectRDMAWrites ( CUflushGPUDirectRDMAWritesTarget target , CUflushGPUDirectRDMAWritesScope scope ) ;
CUresult  cuFuncGetAttribute ( int * pi , CUfunction_attribute attrib , CUfunction hfunc ) ;
CUresult  cuFuncGetModule ( CUmodule * hmod , CUfunction hfunc ) ;
CUresult  cuFuncSetAttribute ( CUfunction hfunc , CUfunction_attribute attrib , int value ) ;
CUresult  cuFuncSetCacheConfig ( CUfunction hfunc , CUfunc_cache config ) ;
CUresult  cuFuncSetSharedMemConfig ( CUfunction hfunc , CUsharedconfig config ) ;
CUresult  cuGetErrorName ( CUresult error , const char * * pStr ) ;
CUresult  cuGetErrorString ( CUresult error , const char * * pStr ) ;
CUresult  cuGetProcAddress ( const char * symbol , void * * pfn , int cudaVersion , cuuint64_t flags ) ;
CUresult  cuGraphAddChildGraphNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , CUgraph childGraph ) ;
CUresult  cuGraphAddDependencies ( CUgraph hGraph , const CUgraphNode * from , const CUgraphNode * to , size_t numDependencies ) ;
CUresult  cuGraphAddEmptyNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies ) ;
CUresult  cuGraphAddEventRecordNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , CUevent event ) ;
CUresult  cuGraphAddEventWaitNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , CUevent event ) ;
CUresult  cuGraphAddExternalSemaphoresSignalNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphAddExternalSemaphoresWaitNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const CUDA_EXT_SEM_WAIT_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphAddHostNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const CUDA_HOST_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphAddKernelNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const CUDA_KERNEL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphAddMemAllocNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , CUDA_MEM_ALLOC_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphAddMemFreeNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , CUdeviceptr dptr ) ;
CUresult  cuGraphAddMemcpyNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const CUDA_MEMCPY3D * copyParams , CUcontext ctx ) ;
CUresult  cuGraphAddMemsetNode ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const CUDA_MEMSET_NODE_PARAMS * memsetParams , CUcontext ctx ) ;
CUresult  cuGraphChildGraphNodeGetGraph ( CUgraphNode hNode , CUgraph * phGraph ) ;
CUresult  cuGraphClone ( CUgraph * phGraphClone , CUgraph originalGraph ) ;
CUresult  cuGraphCreate ( CUgraph * phGraph , unsigned int flags ) ;
CUresult  cuGraphDebugDotPrint ( CUgraph hGraph , const char * path , unsigned int flags ) ;
CUresult  cuGraphDestroy ( CUgraph hGraph ) ;
CUresult  cuGraphDestroyNode ( CUgraphNode hNode ) ;
CUresult  cuGraphEventRecordNodeGetEvent ( CUgraphNode hNode , CUevent * event_out ) ;
CUresult  cuGraphEventRecordNodeSetEvent ( CUgraphNode hNode , CUevent event ) ;
CUresult  cuGraphEventWaitNodeGetEvent ( CUgraphNode hNode , CUevent * event_out ) ;
CUresult  cuGraphEventWaitNodeSetEvent ( CUgraphNode hNode , CUevent event ) ;
CUresult  cuGraphExecChildGraphNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , CUgraph childGraph ) ;
CUresult  cuGraphExecDestroy ( CUgraphExec hGraphExec ) ;
CUresult  cuGraphExecEventRecordNodeSetEvent ( CUgraphExec hGraphExec , CUgraphNode hNode , CUevent event ) ;
CUresult  cuGraphExecEventWaitNodeSetEvent ( CUgraphExec hGraphExec , CUgraphNode hNode , CUevent event ) ;
CUresult  cuGraphExecExternalSemaphoresSignalNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphExecExternalSemaphoresWaitNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , const CUDA_EXT_SEM_WAIT_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphExecHostNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , const CUDA_HOST_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphExecKernelNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , const CUDA_KERNEL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphExecMemcpyNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , const CUDA_MEMCPY3D * copyParams , CUcontext ctx ) ;
CUresult  cuGraphExecMemsetNodeSetParams ( CUgraphExec hGraphExec , CUgraphNode hNode , const CUDA_MEMSET_NODE_PARAMS * memsetParams , CUcontext ctx ) ;
CUresult  cuGraphExecUpdate ( CUgraphExec hGraphExec , CUgraph hGraph , CUgraphNode * hErrorNode_out , CUgraphExecUpdateResult * updateResult_out ) ;
CUresult  cuGraphExternalSemaphoresSignalNodeGetParams ( CUgraphNode hNode , CUDA_EXT_SEM_SIGNAL_NODE_PARAMS * params_out ) ;
CUresult  cuGraphExternalSemaphoresSignalNodeSetParams ( CUgraphNode hNode , const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphExternalSemaphoresWaitNodeGetParams ( CUgraphNode hNode , CUDA_EXT_SEM_WAIT_NODE_PARAMS * params_out ) ;
CUresult  cuGraphExternalSemaphoresWaitNodeSetParams ( CUgraphNode hNode , const CUDA_EXT_SEM_WAIT_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphGetEdges ( CUgraph hGraph , CUgraphNode * from , CUgraphNode * to , size_t * numEdges ) ;
CUresult  cuGraphGetNodes ( CUgraph hGraph , CUgraphNode * nodes , size_t * numNodes ) ;
CUresult  cuGraphGetRootNodes ( CUgraph hGraph , CUgraphNode * rootNodes , size_t * numRootNodes ) ;
CUresult  cuGraphHostNodeGetParams ( CUgraphNode hNode , CUDA_HOST_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphHostNodeSetParams ( CUgraphNode hNode , const CUDA_HOST_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphInstantiate ( CUgraphExec * phGraphExec , CUgraph hGraph , CUgraphNode * phErrorNode , char * logBuffer , size_t bufferSize ) ;
CUresult  cuGraphInstantiateWithFlags ( CUgraphExec * phGraphExec , CUgraph hGraph , unsigned long long flags ) ;
CUresult  cuGraphKernelNodeCopyAttributes ( CUgraphNode dst , CUgraphNode src ) ;
CUresult  cuGraphKernelNodeGetAttribute ( CUgraphNode hNode , CUkernelNodeAttrID attr , CUkernelNodeAttrValue * value_out ) ;
CUresult  cuGraphKernelNodeGetParams ( CUgraphNode hNode , CUDA_KERNEL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphKernelNodeSetAttribute ( CUgraphNode hNode , CUkernelNodeAttrID attr , const CUkernelNodeAttrValue * value ) ;
CUresult  cuGraphKernelNodeSetParams ( CUgraphNode hNode , const CUDA_KERNEL_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphLaunch ( CUgraphExec hGraphExec , CUstream hStream ) ;
CUresult  cuGraphMemAllocNodeGetParams ( CUgraphNode hNode , CUDA_MEM_ALLOC_NODE_PARAMS * params_out ) ;
CUresult  cuGraphMemFreeNodeGetParams ( CUgraphNode hNode , CUdeviceptr * dptr_out ) ;
CUresult  cuGraphMemcpyNodeGetParams ( CUgraphNode hNode , CUDA_MEMCPY3D * nodeParams ) ;
CUresult  cuGraphMemcpyNodeSetParams ( CUgraphNode hNode , const CUDA_MEMCPY3D * nodeParams ) ;
CUresult  cuGraphMemsetNodeGetParams ( CUgraphNode hNode , CUDA_MEMSET_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphMemsetNodeSetParams ( CUgraphNode hNode , const CUDA_MEMSET_NODE_PARAMS * nodeParams ) ;
CUresult  cuGraphNodeFindInClone ( CUgraphNode * phNode , CUgraphNode hOriginalNode , CUgraph hClonedGraph ) ;
CUresult  cuGraphNodeGetDependencies ( CUgraphNode hNode , CUgraphNode * dependencies , size_t * numDependencies ) ;
CUresult  cuGraphNodeGetDependentNodes ( CUgraphNode hNode , CUgraphNode * dependentNodes , size_t * numDependentNodes ) ;
CUresult  cuGraphNodeGetType ( CUgraphNode hNode , CUgraphNodeType * type ) ;
CUresult  cuGraphReleaseUserObject ( CUgraph graph , CUuserObject object , unsigned int count ) ;
CUresult  cuGraphRemoveDependencies ( CUgraph hGraph , const CUgraphNode * from , const CUgraphNode * to , size_t numDependencies ) ;
CUresult  cuGraphRetainUserObject ( CUgraph graph , CUuserObject object , unsigned int count , unsigned int flags ) ;
CUresult  cuGraphUpload ( CUgraphExec hGraphExec , CUstream hStream ) ;
CUresult  cuGraphicsMapResources ( unsigned int count , CUgraphicsResource * resources , CUstream hStream ) ;
CUresult  cuGraphicsResourceGetMappedMipmappedArray ( CUmipmappedArray * pMipmappedArray , CUgraphicsResource resource ) ;
CUresult  cuGraphicsResourceGetMappedPointer ( CUdeviceptr * pDevPtr , size_t * pSize , CUgraphicsResource resource ) ;
CUresult  cuGraphicsResourceSetMapFlags ( CUgraphicsResource resource , unsigned int flags ) ;
CUresult  cuGraphicsSubResourceGetMappedArray ( CUarray * pArray , CUgraphicsResource resource , unsigned int arrayIndex , unsigned int mipLevel ) ;
CUresult  cuGraphicsUnmapResources ( unsigned int count , CUgraphicsResource * resources , CUstream hStream ) ;
CUresult  cuGraphicsUnregisterResource ( CUgraphicsResource resource ) ;
CUresult  cuImportExternalMemory ( CUexternalMemory * extMem_out , const CUDA_EXTERNAL_MEMORY_HANDLE_DESC * memHandleDesc ) ;
CUresult  cuImportExternalSemaphore ( CUexternalSemaphore * extSem_out , const CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC * semHandleDesc ) ;
CUresult  cuInit ( unsigned int Flags ) ;
CUresult  cuIpcCloseMemHandle ( CUdeviceptr dptr ) ;
CUresult  cuIpcGetEventHandle ( CUipcEventHandle * pHandle , CUevent event ) ;
CUresult  cuIpcGetMemHandle ( CUipcMemHandle * pHandle , CUdeviceptr dptr ) ;
CUresult  cuIpcOpenEventHandle ( CUevent * phEvent , CUipcEventHandle handle ) ;
CUresult  cuIpcOpenMemHandle ( CUdeviceptr * pdptr , CUipcMemHandle handle , unsigned int Flags ) ;
CUresult  cuLaunchCooperativeKernel ( CUfunction f , unsigned int gridDimX , unsigned int gridDimY , unsigned int gridDimZ , unsigned int blockDimX , unsigned int blockDimY , unsigned int blockDimZ , unsigned int sharedMemBytes , CUstream hStream , void * * kernelParams ) ;
CUresult  cuLaunchHostFunc ( CUstream hStream , CUhostFn fn , void * userData ) ;
CUresult  cuLaunchKernel ( CUfunction f , unsigned int gridDimX , unsigned int gridDimY , unsigned int gridDimZ , unsigned int blockDimX , unsigned int blockDimY , unsigned int blockDimZ , unsigned int sharedMemBytes , CUstream hStream , void * * kernelParams , void * * extra ) ;
CUresult  cuLinkAddData ( CUlinkState state , CUjitInputType type , void * data , size_t size , const char * name , unsigned int numOptions , CUjit_option * options , void * * optionValues ) ;
CUresult  cuLinkAddFile ( CUlinkState state , CUjitInputType type , const char * path , unsigned int numOptions , CUjit_option * options , void * * optionValues ) ;
CUresult  cuLinkComplete ( CUlinkState state , void * * cubinOut , size_t * sizeOut ) ;
CUresult  cuLinkCreate ( unsigned int numOptions , CUjit_option * options , void * * optionValues , CUlinkState * stateOut ) ;
CUresult  cuLinkDestroy ( CUlinkState state ) ;
CUresult  cuMemAddressFree ( CUdeviceptr ptr , size_t size ) ;
CUresult  cuMemAddressReserve ( CUdeviceptr * ptr , size_t size , size_t alignment , CUdeviceptr addr , unsigned long long flags ) ;
CUresult  cuMemAdvise ( CUdeviceptr devPtr , size_t count , CUmem_advise advice , CUdevice device ) ;
CUresult  cuMemAlloc ( CUdeviceptr * dptr , size_t bytesize ) ;
CUresult  cuMemAllocAsync ( CUdeviceptr * dptr , size_t bytesize , CUstream hStream ) ;
CUresult  cuMemAllocFromPoolAsync ( CUdeviceptr * dptr , size_t bytesize , CUmemoryPool pool , CUstream hStream ) ;
CUresult  cuMemAllocHost ( void * * pp , size_t bytesize ) ;
CUresult  cuMemAllocManaged ( CUdeviceptr * dptr , size_t bytesize , unsigned int flags ) ;
CUresult  cuMemAllocPitch ( CUdeviceptr * dptr , size_t * pPitch , size_t WidthInBytes , size_t Height , unsigned int ElementSizeBytes ) ;
CUresult  cuMemCreate ( CUmemGenericAllocationHandle * handle , size_t size , const CUmemAllocationProp * prop , unsigned long long flags ) ;
CUresult  cuMemExportToShareableHandle ( void * shareableHandle , CUmemGenericAllocationHandle handle , CUmemAllocationHandleType handleType , unsigned long long flags ) ;
CUresult  cuMemFree ( CUdeviceptr dptr ) ;
CUresult  cuMemFreeAsync ( CUdeviceptr dptr , CUstream hStream ) ;
CUresult  cuMemFreeHost ( void * p ) ;
CUresult  cuMemGetAccess ( unsigned long long * flags , const CUmemLocation * location , CUdeviceptr ptr ) ;
CUresult  cuMemGetAddressRange ( CUdeviceptr * pbase , size_t * psize , CUdeviceptr dptr ) ;
CUresult  cuMemGetAllocationGranularity ( size_t * granularity , const CUmemAllocationProp * prop , CUmemAllocationGranularity_flags option ) ;
CUresult  cuMemGetAllocationPropertiesFromHandle ( CUmemAllocationProp * prop , CUmemGenericAllocationHandle handle ) ;
CUresult  cuMemGetInfo ( size_t * free , size_t * total ) ;
CUresult  cuMemHostAlloc ( void * * pp , size_t bytesize , unsigned int Flags ) ;
CUresult  cuMemHostGetDevicePointer ( CUdeviceptr * pdptr , void * p , unsigned int Flags ) ;
CUresult  cuMemHostGetFlags ( unsigned int * pFlags , void * p ) ;
CUresult  cuMemHostRegister ( void * p , size_t bytesize , unsigned int Flags ) ;
CUresult  cuMemHostUnregister ( void * p ) ;
CUresult  cuMemImportFromShareableHandle ( CUmemGenericAllocationHandle * handle , void * osHandle , CUmemAllocationHandleType shHandleType ) ;
CUresult  cuMemMap ( CUdeviceptr ptr , size_t size , size_t vgpu_offset , CUmemGenericAllocationHandle handle , unsigned long long flags ) ;
CUresult  cuMemMapArrayAsync ( CUarrayMapInfo * mapInfoList , unsigned int count , CUstream hStream ) ;
CUresult  cuMemPoolCreate ( CUmemoryPool * pool , const CUmemPoolProps * poolProps ) ;
CUresult  cuMemPoolDestroy ( CUmemoryPool pool ) ;
CUresult  cuMemPoolExportPointer ( CUmemPoolPtrExportData * shareData_out , CUdeviceptr ptr ) ;
CUresult  cuMemPoolExportToShareableHandle ( void * handle_out , CUmemoryPool pool , CUmemAllocationHandleType handleType , unsigned long long flags ) ;
CUresult  cuMemPoolGetAccess ( CUmemAccess_flags * flags , CUmemoryPool memPool , CUmemLocation * location ) ;
CUresult  cuMemPoolGetAttribute ( CUmemoryPool pool , CUmemPool_attribute attr , void * value ) ;
CUresult  cuMemPoolImportFromShareableHandle ( CUmemoryPool * pool_out , void * handle , CUmemAllocationHandleType handleType , unsigned long long flags ) ;
CUresult  cuMemPoolImportPointer ( CUdeviceptr * ptr_out , CUmemoryPool pool , CUmemPoolPtrExportData * shareData ) ;
CUresult  cuMemPoolSetAccess ( CUmemoryPool pool , const CUmemAccessDesc * map , size_t count ) ;
CUresult  cuMemPoolSetAttribute ( CUmemoryPool pool , CUmemPool_attribute attr , void * value ) ;
CUresult  cuMemPoolTrimTo ( CUmemoryPool pool , size_t minBytesToKeep ) ;
CUresult  cuMemPrefetchAsync ( CUdeviceptr devPtr , size_t count , CUdevice dstDevice , CUstream hStream ) ;
CUresult  cuMemRangeGetAttribute ( void * data , size_t dataSize , CUmem_range_attribute attribute , CUdeviceptr devPtr , size_t count ) ;
CUresult  cuMemRangeGetAttributes ( void * * data , size_t * dataSizes , CUmem_range_attribute * attributes , size_t numAttributes , CUdeviceptr devPtr , size_t count ) ;
CUresult  cuMemRelease ( CUmemGenericAllocationHandle handle ) ;
CUresult  cuMemRetainAllocationHandle ( CUmemGenericAllocationHandle * handle , void * addr ) ;
CUresult  cuMemSetAccess ( CUdeviceptr ptr , size_t size , const CUmemAccessDesc * desc , size_t count ) ;
CUresult  cuMemUnmap ( CUdeviceptr ptr , size_t size ) ;
CUresult  cuMemcpy ( CUdeviceptr dst , CUdeviceptr src , size_t ByteCount ) ;
CUresult  cuMemcpy2D ( const CUDA_MEMCPY2D * pCopy ) ;
CUresult  cuMemcpy2DAsync ( const CUDA_MEMCPY2D * pCopy , CUstream hStream ) ;
CUresult  cuMemcpy2DUnaligned ( const CUDA_MEMCPY2D * pCopy ) ;
CUresult  cuMemcpy3D ( const CUDA_MEMCPY3D * pCopy ) ;
CUresult  cuMemcpy3DAsync ( const CUDA_MEMCPY3D * pCopy , CUstream hStream ) ;
CUresult  cuMemcpy3DPeer ( const CUDA_MEMCPY3D_PEER * pCopy ) ;
CUresult  cuMemcpy3DPeerAsync ( const CUDA_MEMCPY3D_PEER * pCopy , CUstream hStream ) ;
CUresult  cuMemcpyAsync ( CUdeviceptr dst , CUdeviceptr src , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemcpyAtoA ( CUarray dstArray , size_t dstOffset , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult  cuMemcpyAtoD ( CUdeviceptr dstDevice , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult  cuMemcpyAtoH ( void * dstHost , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult  cuMemcpyAtoHAsync ( void * dstHost , CUarray srcArray , size_t srcOffset , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemcpyDtoA ( CUarray dstArray , size_t dstOffset , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult  cuMemcpyDtoD ( CUdeviceptr dstDevice , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult  cuMemcpyDtoDAsync ( CUdeviceptr dstDevice , CUdeviceptr srcDevice , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemcpyDtoH ( void * dstHost , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult  cuMemcpyDtoHAsync ( void * dstHost , CUdeviceptr srcDevice , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemcpyHtoA ( CUarray dstArray , size_t dstOffset , const void * srcHost , size_t ByteCount ) ;
CUresult  cuMemcpyHtoAAsync ( CUarray dstArray , size_t dstOffset , const void * srcHost , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemcpyHtoD ( CUdeviceptr dstDevice , const void * srcHost , size_t ByteCount ) ;
CUresult  cuMemcpyHtoDAsync ( CUdeviceptr dstDevice , const void * srcHost , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemcpyPeer ( CUdeviceptr dstDevice , CUcontext dstContext , CUdeviceptr srcDevice , CUcontext srcContext , size_t ByteCount ) ;
CUresult  cuMemcpyPeerAsync ( CUdeviceptr dstDevice , CUcontext dstContext , CUdeviceptr srcDevice , CUcontext srcContext , size_t ByteCount , CUstream hStream ) ;
CUresult  cuMemsetD16 ( CUdeviceptr dstDevice , unsigned short us , size_t N ) ;
CUresult  cuMemsetD16Async ( CUdeviceptr dstDevice , unsigned short us , size_t N , CUstream hStream ) ;
CUresult  cuMemsetD2D16 ( CUdeviceptr dstDevice , size_t dstPitch , unsigned short us , size_t Width , size_t Height ) ;
CUresult  cuMemsetD2D16Async ( CUdeviceptr dstDevice , size_t dstPitch , unsigned short us , size_t Width , size_t Height , CUstream hStream ) ;
CUresult  cuMemsetD2D32 ( CUdeviceptr dstDevice , size_t dstPitch , unsigned int ui , size_t Width , size_t Height ) ;
CUresult  cuMemsetD2D32Async ( CUdeviceptr dstDevice , size_t dstPitch , unsigned int ui , size_t Width , size_t Height , CUstream hStream ) ;
CUresult  cuMemsetD2D8 ( CUdeviceptr dstDevice , size_t dstPitch , unsigned char uc , size_t Width , size_t Height ) ;
CUresult  cuMemsetD2D8Async ( CUdeviceptr dstDevice , size_t dstPitch , unsigned char uc , size_t Width , size_t Height , CUstream hStream ) ;
CUresult  cuMemsetD32 ( CUdeviceptr dstDevice , unsigned int ui , size_t N ) ;
CUresult  cuMemsetD32Async ( CUdeviceptr dstDevice , unsigned int ui , size_t N , CUstream hStream ) ;
CUresult  cuMemsetD8 ( CUdeviceptr dstDevice , unsigned char uc , size_t N ) ;
CUresult  cuMemsetD8Async ( CUdeviceptr dstDevice , unsigned char uc , size_t N , CUstream hStream ) ;
CUresult  cuMipmappedArrayCreate ( CUmipmappedArray * pHandle , const CUDA_ARRAY3D_DESCRIPTOR * pMipmappedArrayDesc , unsigned int numMipmapLevels ) ;
CUresult  cuMipmappedArrayDestroy ( CUmipmappedArray hMipmappedArray ) ;
CUresult  cuMipmappedArrayGetLevel ( CUarray * pLevelArray , CUmipmappedArray hMipmappedArray , unsigned int level ) ;
CUresult  cuMipmappedArrayGetSparseProperties ( CUDA_ARRAY_SPARSE_PROPERTIES * sparseProperties , CUmipmappedArray mipmap ) ;
CUresult  cuModuleGetFunction ( CUfunction * hfunc , CUmodule hmod , const char * name ) ;
CUresult  cuModuleGetGlobal ( CUdeviceptr * dptr , size_t * bytes , CUmodule hmod , const char * name ) ;
CUresult  cuModuleGetSurfRef ( CUsurfref * pSurfRef , CUmodule hmod , const char * name ) ;
CUresult  cuModuleGetTexRef ( CUtexref * pTexRef , CUmodule hmod , const char * name ) ;
CUresult  cuModuleLoad ( CUmodule * module , const char * fname ) ;
CUresult  cuModuleLoadData ( CUmodule * module , const void * image ) ;
CUresult  cuModuleLoadDataEx ( CUmodule * module , const void * image , unsigned int numOptions , CUjit_option * options , void * * optionValues ) ;
CUresult  cuModuleLoadFatBinary ( CUmodule * module , const void * fatCubin ) ;
CUresult  cuModuleUnload ( CUmodule hmod ) ;
CUresult  cuOccupancyAvailableDynamicSMemPerBlock ( size_t * dynamicSmemSize , CUfunction func , int numBlocks , int blockSize ) ;
CUresult  cuOccupancyMaxActiveBlocksPerMultiprocessor ( int * numBlocks , CUfunction func , int blockSize , size_t dynamicSMemSize ) ;
CUresult  cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags ( int * numBlocks , CUfunction func , int blockSize , size_t dynamicSMemSize , unsigned int flags ) ;
CUresult  cuOccupancyMaxPotentialBlockSize ( int * minGridSize , int * blockSize , CUfunction func , CUoccupancyB2DSize blockSizeToDynamicSMemSize , size_t dynamicSMemSize , int blockSizeLimit ) ;
CUresult  cuOccupancyMaxPotentialBlockSizeWithFlags ( int * minGridSize , int * blockSize , CUfunction func , CUoccupancyB2DSize blockSizeToDynamicSMemSize , size_t dynamicSMemSize , int blockSizeLimit , unsigned int flags ) ;
CUresult  cuPointerGetAttribute ( void * data , CUpointer_attribute attribute , CUdeviceptr ptr ) ;
CUresult  cuPointerGetAttributes ( unsigned int numAttributes , CUpointer_attribute * attributes , void * * data , CUdeviceptr ptr ) ;
CUresult  cuPointerSetAttribute ( const void * value , CUpointer_attribute attribute , CUdeviceptr ptr ) ;
CUresult  cuSignalExternalSemaphoresAsync ( const CUexternalSemaphore * extSemArray , const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS * paramsArray , unsigned int numExtSems , CUstream stream ) ;
CUresult  cuStreamAddCallback ( CUstream hStream , CUstreamCallback callback , void * userData , unsigned int flags ) ;
CUresult  cuStreamAttachMemAsync ( CUstream hStream , CUdeviceptr dptr , size_t length , unsigned int flags ) ;
CUresult  cuStreamBatchMemOp ( CUstream stream , unsigned int count , CUstreamBatchMemOpParams * paramArray , unsigned int flags ) ;
CUresult  cuStreamBeginCapture ( CUstream hStream , CUstreamCaptureMode mode ) ;
CUresult  cuStreamCopyAttributes ( CUstream dst , CUstream src ) ;
CUresult  cuStreamCreate ( CUstream * phStream , unsigned int Flags ) ;
CUresult  cuStreamCreateWithPriority ( CUstream * phStream , unsigned int flags , int priority ) ;
CUresult  cuStreamDestroy ( CUstream hStream ) ;
CUresult  cuStreamEndCapture ( CUstream hStream , CUgraph * phGraph ) ;
CUresult  cuStreamGetAttribute ( CUstream hStream , CUstreamAttrID attr , CUstreamAttrValue * value_out ) ;
CUresult  cuStreamGetCaptureInfo ( CUstream hStream , CUstreamCaptureStatus * captureStatus_out , cuuint64_t * id_out ) ;
CUresult  cuStreamGetCaptureInfo_v2 ( CUstream hStream , CUstreamCaptureStatus * captureStatus_out , cuuint64_t * id_out , CUgraph * graph_out , const CUgraphNode * * dependencies_out , size_t * numDependencies_out ) ;
CUresult  cuStreamGetCtx ( CUstream hStream , CUcontext * pctx ) ;
CUresult  cuStreamGetFlags ( CUstream hStream , unsigned int * flags ) ;
CUresult  cuStreamGetPriority ( CUstream hStream , int * priority ) ;
CUresult  cuStreamIsCapturing ( CUstream hStream , CUstreamCaptureStatus * captureStatus ) ;
CUresult  cuStreamQuery ( CUstream hStream ) ;
CUresult  cuStreamSetAttribute ( CUstream hStream , CUstreamAttrID attr , const CUstreamAttrValue * value ) ;
CUresult  cuStreamSynchronize ( CUstream hStream ) ;
CUresult  cuStreamUpdateCaptureDependencies ( CUstream hStream , CUgraphNode * dependencies , size_t numDependencies , unsigned int flags ) ;
CUresult  cuStreamWaitEvent ( CUstream hStream , CUevent hEvent , unsigned int Flags ) ;
CUresult  cuStreamWaitValue32 ( CUstream stream , CUdeviceptr addr , cuuint32_t value , unsigned int flags ) ;
CUresult  cuStreamWaitValue64 ( CUstream stream , CUdeviceptr addr , cuuint64_t value , unsigned int flags ) ;
CUresult  cuStreamWriteValue32 ( CUstream stream , CUdeviceptr addr , cuuint32_t value , unsigned int flags ) ;
CUresult  cuStreamWriteValue64 ( CUstream stream , CUdeviceptr addr , cuuint64_t value , unsigned int flags ) ;
CUresult  cuSurfObjectCreate ( CUsurfObject * pSurfObject , const CUDA_RESOURCE_DESC * pResDesc ) ;
CUresult  cuSurfObjectDestroy ( CUsurfObject surfObject ) ;
CUresult  cuSurfObjectGetResourceDesc ( CUDA_RESOURCE_DESC * pResDesc , CUsurfObject surfObject ) ;
CUresult  cuTexObjectCreate ( CUtexObject * pTexObject , const CUDA_RESOURCE_DESC * pResDesc , const CUDA_TEXTURE_DESC * pTexDesc , const CUDA_RESOURCE_VIEW_DESC * pResViewDesc ) ;
CUresult  cuTexObjectDestroy ( CUtexObject texObject ) ;
CUresult  cuTexObjectGetResourceDesc ( CUDA_RESOURCE_DESC * pResDesc , CUtexObject texObject ) ;
CUresult  cuTexObjectGetResourceViewDesc ( CUDA_RESOURCE_VIEW_DESC * pResViewDesc , CUtexObject texObject ) ;
CUresult  cuTexObjectGetTextureDesc ( CUDA_TEXTURE_DESC * pTexDesc , CUtexObject texObject ) ;
CUresult  cuThreadExchangeStreamCaptureMode ( CUstreamCaptureMode * mode ) ;
CUresult  cuUserObjectCreate ( CUuserObject * object_out , void * ptr , CUhostFn destroy , unsigned int initialRefcount , unsigned int flags ) ;
CUresult  cuUserObjectRelease ( CUuserObject object , unsigned int count ) ;
CUresult  cuUserObjectRetain ( CUuserObject object , unsigned int count ) ;
CUresult  cuWaitExternalSemaphoresAsync ( const CUexternalSemaphore * extSemArray , const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS * paramsArray , unsigned int numExtSems , CUstream stream ) ;
CUresult cuArray3DCreate_v2 ( CUarray * pHandle , const CUDA_ARRAY3D_DESCRIPTOR * pAllocateArray ) ;
CUresult cuArrayCreate_v2 ( CUarray * pHandle , const CUDA_ARRAY_DESCRIPTOR * pAllocateArray ) ;
CUresult cuArrayGetDescriptor_v2 ( CUDA_ARRAY_DESCRIPTOR * pArrayDescriptor , CUarray hArray ) ;
CUresult cuCtxCreate_v2 ( CUcontext * pctx , unsigned int flags , CUdevice dev ) ;
CUresult cuCtxDestroy_v2 ( CUcontext ctx ) ;
CUresult cuCtxPopCurrent_v2 ( CUcontext * pctx ) ;
CUresult cuCtxPushCurrent_v2 ( CUcontext ctx ) ;
CUresult cuDevicePrimaryCtxRelease_v2 ( CUdevice dev ) ;
CUresult cuDevicePrimaryCtxReset_v2 ( CUdevice dev ) ;
CUresult cuDevicePrimaryCtxSetFlags_v2 ( CUdevice dev , unsigned int flags ) ;
CUresult cuDeviceTotalMem_v2 ( size_t * bytes , CUdevice dev ) ;
CUresult cuEGLApiInit ( ) ;
CUresult cuEGLInit ( ) ;
CUresult cuEGLStreamConsumerAcquireFrame ( CUeglStreamConnection * conn , CUgraphicsResource * pCudaResource , CUstream * pStream , unsigned int timeout ) ;
CUresult cuEGLStreamConsumerConnect ( CUeglStreamConnection * conn , EGLStreamKHR stream ) ;
CUresult cuEGLStreamConsumerConnectWithFlags ( CUeglStreamConnection * conn , EGLStreamKHR stream , unsigned int flags ) ;
CUresult cuEGLStreamConsumerDisconnect ( CUeglStreamConnection * conn ) ;
CUresult cuEGLStreamConsumerReleaseFrame ( CUeglStreamConnection * conn , CUgraphicsResource pCudaResource , CUstream * pStream ) ;
CUresult cuEGLStreamProducerConnect ( CUeglStreamConnection * conn , EGLStreamKHR stream , EGLint width , EGLint height ) ;
CUresult cuEGLStreamProducerDisconnect ( CUeglStreamConnection * conn ) ;
CUresult cuEGLStreamProducerPresentFrame ( CUeglStreamConnection * conn , CUeglFrame eglframe , CUstream * pStream ) ;
CUresult cuEGLStreamProducerReturnFrame ( CUeglStreamConnection * conn , CUeglFrame * eglframe , CUstream * pStream ) ;
CUresult cuEventDestroy_v2 ( CUevent hEvent ) ;
CUresult cuEventRecordWithFlags_ptsz ( CUevent hEvent , CUstream hStream , unsigned int flags ) ;
CUresult cuEventRecord_ptsz ( CUevent hEvent , CUstream hStream ) ;
CUresult cuGLCtxCreate ( CUcontext * pCtx , unsigned int Flags , CUdevice device ) ;
CUresult cuGLCtxCreate_v2 ( CUcontext * pCtx , unsigned int Flags , CUdevice device ) ;
CUresult cuGLGetDevices ( unsigned int * pCudaDeviceCount , CUdevice * pCudaDevices , unsigned int cudaDeviceCount , CUGLDeviceList deviceList ) ;
CUresult cuGLGetDevices_v2 ( unsigned int * pCudaDeviceCount , CUdevice * pCudaDevices , unsigned int cudaDeviceCount , CUGLDeviceList deviceList ) ;
CUresult cuGLInit ( ) ;
CUresult cuGLMapBufferObject ( CUdeviceptr * dptr , size_t * size , GLuint buffer ) ;
CUresult cuGLMapBufferObjectAsync ( CUdeviceptr * dptr , size_t * size , GLuint buffer , CUstream hStream ) ;
CUresult cuGLMapBufferObjectAsync_v2 ( CUdeviceptr * dptr , size_t * size , GLuint buffer , CUstream hStream ) ;
CUresult cuGLMapBufferObjectAsync_v2_ptsz ( CUdeviceptr * dptr , size_t * size , GLuint buffer , CUstream hStream ) ;
CUresult cuGLMapBufferObject_v2 ( CUdeviceptr * dptr , size_t * size , GLuint buffer ) ;
CUresult cuGLMapBufferObject_v2_ptds ( CUdeviceptr * dptr , size_t * size , GLuint buffer ) ;
CUresult cuGLRegisterBufferObject ( GLuint buffer ) ;
CUresult cuGLSetBufferObjectMapFlags ( GLuint buffer , unsigned int Flags ) ;
CUresult cuGLUnmapBufferObject ( GLuint buffer ) ;
CUresult cuGLUnmapBufferObjectAsync ( GLuint buffer , CUstream hStream ) ;
CUresult cuGLUnregisterBufferObject ( GLuint buffer ) ;
CUresult cuGetExportTable ( const void * * * ppExportTable , const CUuuid * pExportTableId ) ;
CUresult cuGetProcAddress_alt ( const char * symbol , void * * pfn , int cudaVersion , cuuint64_t flags ) ;
CUresult cuGetProcAddress_v2 ( const char * symbol , void * * pfn , int driverVersion , cuuint64_t flags , CUdriverProcAddressQueryResult * symbolStatus ) ;
CUresult cuGetProcAddress_v2_alt ( const char * symbol , void * * pfn , int driverVersion , cuuint64_t flags , CUdriverProcAddressQueryResult * symbolStatus ) ;
CUresult cuGraphAddKernelNode_v2 ( CUgraphNode * phGraphNode , CUgraph hGraph , const CUgraphNode * dependencies , size_t numDependencies , const void * nodeParams ) ;
CUresult cuGraphInstantiate_v2 ( CUgraphExec * phGraphExec , CUgraph hGraph , CUgraphNode * phErrorNode , char * logBuffer , size_t bufferSize ) ;
CUresult cuGraphKernelNodeGetParams_v2 ( CUgraphNode hNode , void * nodeParams ) ;
CUresult cuGraphKernelNodeSetParams_v2 ( CUgraphNode hNode , const void * nodeParams ) ;
CUresult cuGraphLaunch_ptsz ( CUgraphExec hGraphExec , CUstream hStream ) ;
CUresult cuGraphUpload_ptsz ( CUgraphExec hGraphExec , CUstream hStream ) ;
CUresult cuGraphicsEGLRegisterImage ( CUgraphicsResource * pCudaResource , EGLImageKHR image , unsigned int flags ) ;
CUresult cuGraphicsGLRegisterBuffer ( CUgraphicsResource * pCudaResource , GLuint buffer , unsigned int Flags ) ;
CUresult cuGraphicsGLRegisterImage ( CUgraphicsResource * pCudaResource , GLuint image , GLenum target , unsigned int Flags ) ;
CUresult cuGraphicsMapResources_ptsz ( unsigned int count , CUgraphicsResource * resources , CUstream hStream ) ;
CUresult cuGraphicsResourceGetMappedEglFrame ( CUeglFrame * eglFrame , CUgraphicsResource resource , unsigned int index , unsigned int mipLevel ) ;
CUresult cuGraphicsResourceGetMappedPointer_v2 ( CUdeviceptr * pDevPtr , size_t * pSize , CUgraphicsResource resource ) ;
CUresult cuGraphicsResourceSetMapFlags_v2 ( CUgraphicsResource resource , unsigned int flags ) ;
CUresult cuGraphicsUnmapResources_ptsz ( unsigned int count , CUgraphicsResource * resources , CUstream hStream ) ;
CUresult cuGraphicsVDPAURegisterOutputSurface ( CUgraphicsResource * pCudaResource , VdpOutputSurface vdpSurface , unsigned int flags ) ;
CUresult cuGraphicsVDPAURegisterVideoSurface ( CUgraphicsResource * pCudaResource , VdpVideoSurface vdpSurface , unsigned int flags ) ;
CUresult cuIpcOpenMemHandle_v2 ( CUdeviceptr * pdptr , CUipcMemHandle handle , unsigned int Flags ) ;
CUresult cuLaunchHostFunc_ptsz ( CUstream hStream , CUhostFn fn , void * userData ) ;
CUresult cuLinkAddData_v2 ( CUlinkState state , CUjitInputType type , void * data , size_t size , const char * name , unsigned int numOptions , CUjit_option * options , void * * optionValues ) ;
CUresult cuLinkAddFile_v2 ( CUlinkState state , CUjitInputType type , const char * path , unsigned int numOptions , CUjit_option * options , void * * optionValues ) ;
CUresult cuLinkCreate_v2 ( unsigned int numOptions , CUjit_option * options , void * * optionValues , CUlinkState * stateOut ) ;
CUresult cuMemAllocAsync_ptsz ( CUdeviceptr * dptr , size_t bytesize , CUstream hStream ) ;
CUresult cuMemAllocFromPoolAsync_ptsz ( CUdeviceptr * dptr , size_t bytesize , CUmemoryPool pool , CUstream hStream ) ;
CUresult cuMemAllocHost_v2 ( void * * pp , size_t bytesize ) ;
CUresult cuMemAllocPitch_v2 ( CUdeviceptr * dptr , size_t * pPitch , size_t WidthInBytes , size_t Height , unsigned int ElementSizeBytes ) ;
CUresult cuMemAlloc_v2 ( CUdeviceptr * dptr , size_t bytesize ) ;
CUresult cuMemFreeAsync_ptsz ( CUdeviceptr dptr , CUstream hStream ) ;
CUresult cuMemFree_v2 ( CUdeviceptr dptr ) ;
CUresult cuMemGetAddressRange_v2 ( CUdeviceptr * pbase , size_t * psize , CUdeviceptr dptr ) ;
CUresult cuMemGetInfo_v2 ( size_t * free , size_t * total ) ;
CUresult cuMemHostGetDevicePointer_v2 ( CUdeviceptr * pdptr , void * p , unsigned int Flags ) ;
CUresult cuMemHostRegister_v2 ( void * p , size_t bytesize , unsigned int Flags ) ;
CUresult cuMemMapArrayAsync_ptsz ( CUarrayMapInfo * mapInfoList , unsigned int count , CUstream hStream ) ;
CUresult cuMemPrefetchAsync_ptsz ( CUdeviceptr devPtr , size_t count , CUdevice dstDevice , CUstream hStream ) ;
CUresult cuMemcpy2DAsync_v2 ( const CUDA_MEMCPY2D * pCopy , CUstream hStream ) ;
CUresult cuMemcpy2DAsync_v2_ptsz ( const CUDA_MEMCPY2D * pCopy , CUstream hStream ) ;
CUresult cuMemcpy2DUnaligned_v2 ( const CUDA_MEMCPY2D * pCopy ) ;
CUresult cuMemcpy2DUnaligned_v2_ptds ( const CUDA_MEMCPY2D * pCopy ) ;
CUresult cuMemcpy2D_v2 ( const CUDA_MEMCPY2D * pCopy ) ;
CUresult cuMemcpy3DAsync_v2 ( const CUDA_MEMCPY3D * pCopy , CUstream hStream ) ;
CUresult cuMemcpy3DAsync_v2_ptsz ( const CUDA_MEMCPY3D * pCopy , CUstream hStream ) ;
CUresult cuMemcpy3DPeerAsync_ptsz ( const CUDA_MEMCPY3D_PEER * pCopy , CUstream hStream ) ;
CUresult cuMemcpy3DPeer_ptds ( const CUDA_MEMCPY3D_PEER * pCopy ) ;
CUresult cuMemcpy3D_v2 ( const CUDA_MEMCPY3D * pCopy ) ;
CUresult cuMemcpy3D_v2_ptds ( const CUDA_MEMCPY3D * pCopy ) ;
CUresult cuMemcpyAsync_ptsz ( CUdeviceptr dst , CUdeviceptr src , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyAtoA_v2 ( CUarray dstArray , size_t dstOffset , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult cuMemcpyAtoA_v2_ptds ( CUarray dstArray , size_t dstOffset , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult cuMemcpyAtoD_v2 ( CUdeviceptr dstDevice , CUarray a2 , size_t ByteCount , size_t a4 ) ;
CUresult cuMemcpyAtoD_v2_ptds ( CUdeviceptr dstDevice , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult cuMemcpyAtoHAsync_v2 ( void * dstHost , CUarray srcArray , size_t srcOffset , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyAtoHAsync_v2_ptsz ( void * dstHost , CUarray srcArray , size_t srcOffset , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyAtoH_v2 ( void * dstHost , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult cuMemcpyAtoH_v2_ptds ( void * dstHost , CUarray srcArray , size_t srcOffset , size_t ByteCount ) ;
CUresult cuMemcpyDtoA_v2 ( CUarray dstArray , size_t dstOffset , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult cuMemcpyDtoA_v2_ptds ( CUarray dstArray , size_t dstOffset , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult cuMemcpyDtoDAsync_v2 ( CUdeviceptr dstDevice , CUdeviceptr srcDevice , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyDtoDAsync_v2_ptsz ( CUdeviceptr dstDevice , CUdeviceptr srcDevice , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyDtoD_v2 ( CUdeviceptr dstDevice , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult cuMemcpyDtoD_v2_ptds ( CUdeviceptr dstDevice , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult cuMemcpyDtoHAsync_v2 ( void * dstHost , CUdeviceptr srcDevice , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyDtoHAsync_v2_ptsz ( void * dstHost , CUdeviceptr srcDevice , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyDtoH_v2 ( void * dstHost , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult cuMemcpyDtoH_v2_ptds ( void * dstHost , CUdeviceptr srcDevice , size_t ByteCount ) ;
CUresult cuMemcpyHtoAAsync_v2 ( CUarray dstArray , size_t dstOffset , const void * srcHost , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyHtoAAsync_v2_ptsz ( CUarray dstArray , size_t dstOffset , const void * srcHost , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyHtoA_v2 ( CUarray dstArray , size_t dstOffset , const void * srcHost , size_t ByteCount ) ;
CUresult cuMemcpyHtoA_v2_ptds ( CUarray dstArray , size_t dstOffset , const void * srcHost , size_t ByteCount ) ;
CUresult cuMemcpyHtoDAsync_v2 ( CUdeviceptr dstDevice , const void * srcHost , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyHtoDAsync_v2_ptsz ( CUdeviceptr dstDevice , const void * srcHost , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyHtoD_v2 ( CUdeviceptr dstDevice , const void * srcHost , size_t ByteCount ) ;
CUresult cuMemcpyHtoD_v2_ptds ( CUdeviceptr dstDevice , const void * srcHost , size_t ByteCount ) ;
CUresult cuMemcpyPeerAsync_ptsz ( CUdeviceptr dstDevice , CUcontext dstContext , CUdeviceptr srcDevice , CUcontext srcContext , size_t ByteCount , CUstream hStream ) ;
CUresult cuMemcpyPeer_ptds ( CUdeviceptr dstDevice , CUcontext dstContext , CUdeviceptr srcDevice , CUcontext srcContext , size_t ByteCount ) ;
CUresult cuMemcpy_ptds ( CUdeviceptr dst , CUdeviceptr src , size_t ByteCount ) ;
CUresult cuMemoryFree ( void * ptr , size_t size ) ;
CUresult cuMemsetD16Async_ptsz ( CUdeviceptr dstDevice , unsigned short us , size_t N , CUstream hStream ) ;
CUresult cuMemsetD16_v2 ( CUdeviceptr dstDevice , unsigned short us , size_t N ) ;
CUresult cuMemsetD16_v2_ptds ( CUdeviceptr dstDevice , unsigned short us , size_t N ) ;
CUresult cuMemsetD2D16Async_ptsz ( CUdeviceptr dstDevice , size_t dstPitch , unsigned short us , size_t Width , size_t Height , CUstream hStream ) ;
CUresult cuMemsetD2D16_v2 ( CUdeviceptr dstDevice , size_t dstPitch , unsigned short us , size_t Width , size_t Height ) ;
CUresult cuMemsetD2D16_v2_ptds ( CUdeviceptr dstDevice , size_t dstPitch , unsigned short us , size_t Width , size_t Height ) ;
CUresult cuMemsetD2D32Async_ptsz ( CUdeviceptr dstDevice , size_t dstPitch , unsigned int ui , size_t Width , size_t Height , CUstream hStream ) ;
CUresult cuMemsetD2D32_v2 ( CUdeviceptr dstDevice , size_t dstPitch , unsigned int ui , size_t Width , size_t Height ) ;
CUresult cuMemsetD2D32_v2_ptds ( CUdeviceptr dstDevice , size_t dstPitch , unsigned int ui , size_t Width , size_t Height ) ;
CUresult cuMemsetD2D8Async_ptsz ( CUdeviceptr dstDevice , size_t dstPitch , unsigned char uc , size_t Width , size_t Height , CUstream hStream ) ;
CUresult cuMemsetD2D8_v2 ( CUdeviceptr dstDevice , size_t dstPitch , unsigned char uc , size_t Width , size_t Height ) ;
CUresult cuMemsetD2D8_v2_ptds ( CUdeviceptr dstDevice , size_t dstPitch , unsigned char uc , size_t Width , size_t Height ) ;
CUresult cuMemsetD32Async_ptsz ( CUdeviceptr dstDevice , unsigned int ui , size_t N , CUstream hStream ) ;
CUresult cuMemsetD32_v2 ( CUdeviceptr dstDevice , unsigned int ui , size_t N ) ;
CUresult cuMemsetD32_v2_ptds ( CUdeviceptr dstDevice , unsigned int ui , size_t N ) ;
CUresult cuMemsetD8Async_ptsz ( CUdeviceptr dstDevice , unsigned char uc , size_t N , CUstream hStream ) ;
CUresult cuMemsetD8_v2 ( CUdeviceptr dstDevice , unsigned char uc , size_t N ) ;
CUresult cuMemsetD8_v2_ptds ( CUdeviceptr dstDevice , unsigned char uc , size_t N ) ;
CUresult cuModuleGetGlobal_v2 ( CUdeviceptr * dptr , size_t * bytes , CUmodule hmod , const char * name ) ;
CUresult cuProfilerInitialize ( const char * configFile , const char * outputFile , CUoutput_mode outputMode ) ;
CUresult cuProfilerStart ( ) ;
CUresult cuProfilerStop ( ) ;
CUresult cuSignalExternalSemaphoresAsync_ptsz ( const CUexternalSemaphore * extSemArray , const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS * paramsArray , unsigned int numExtSems , CUstream stream ) ;
CUresult cuStreamAddCallback_ptsz ( CUstream hStream , CUstreamCallback callback , void * userData , unsigned int flags ) ;
CUresult cuStreamAttachMemAsync_ptsz ( CUstream hStream , CUdeviceptr dptr , size_t length , unsigned int flags ) ;
CUresult cuStreamBatchMemOp_ptsz ( CUstream stream , unsigned int count , CUstreamBatchMemOpParams * paramArray , unsigned int flags ) ;
CUresult cuStreamBeginCapture_ptsz ( CUstream hStream , CUstreamCaptureMode mode ) ;
CUresult cuStreamBeginCapture_v2 ( CUstream hStream ) ;
CUresult cuStreamBeginCapture_v2_ptsz ( CUstream hStream ) ;
CUresult cuStreamCopyAttributes_ptsz ( CUstream dst , CUstream src ) ;
CUresult cuStreamDestroy_v2 ( CUstream hStream ) ;
CUresult cuStreamEndCapture_ptsz ( CUstream hStream , CUgraph * phGraph ) ;
CUresult cuStreamGetAttribute_ptsz ( CUstream hStream , CUstreamAttrID attr , CUstreamAttrValue * value_out ) ;
CUresult cuStreamGetCaptureInfo_ptsz ( CUstream hStream , CUstreamCaptureStatus * captureStatus , cuuint64_t * id ) ;
CUresult cuStreamGetCaptureInfo_v2_ptsz ( CUstream hStream , CUstreamCaptureStatus * captureStatus , cuuint64_t * id ) ;
CUresult cuStreamGetCtx_ptsz ( CUstream hStream , CUcontext * pctx ) ;
CUresult cuStreamGetFlags_ptsz ( CUstream hStream , unsigned int * flags ) ;
CUresult cuStreamGetPriority_ptsz ( CUstream hStream , int * priority ) ;
CUresult cuStreamIsCapturing_ptsz ( CUstream hStream , CUstreamCaptureStatus * captureStatus ) ;
CUresult cuStreamQuery_ptsz ( CUstream hStream ) ;
CUresult cuStreamSetAttribute_ptsz ( CUstream hStream , CUstreamAttrID attr , const CUstreamAttrValue * value ) ;
CUresult cuStreamSynchronize_ptsz ( CUstream hStream ) ;
CUresult cuStreamUpdateCaptureDependencies_ptsz ( CUstream hStream , CUgraphNode * dependencies , size_t numDependencies , unsigned int flags ) ;
CUresult cuStreamWaitEvent_ptsz ( CUstream hStream , CUevent hEvent , unsigned int Flags ) ;
CUresult cuStreamWaitValue32_ptsz ( CUstream stream , CUdeviceptr addr , cuuint32_t value , unsigned int flags ) ;
CUresult cuStreamWaitValue64_ptsz ( CUstream stream , CUdeviceptr addr , cuuint64_t value , unsigned int flags ) ;
CUresult cuStreamWriteValue32_ptsz ( CUstream stream , CUdeviceptr addr , cuuint32_t value , unsigned int flags ) ;
CUresult cuStreamWriteValue64_ptsz ( CUstream stream , CUdeviceptr addr , cuuint64_t value , unsigned int flags ) ;
CUresult cuTexRefGetAddress_v2 ( CUdeviceptr * pdptr , CUtexref hTexRef ) ;
CUresult cuTexRefSetAddress2D_v2 ( CUtexref hTexRef , const CUDA_ARRAY_DESCRIPTOR * desc , CUdeviceptr dptr , size_t Pitch ) ;
CUresult cuTexRefSetAddress2D_v3 ( CUtexref hTexRef , const CUDA_ARRAY_DESCRIPTOR * desc , CUdeviceptr dptr , size_t Pitch ) ;
CUresult cuTexRefSetAddress_v2 ( size_t * ByteOffset , CUtexref hTexRef , CUdeviceptr dptr , size_t bytes ) ;
CUresult cuVDPAUCtxCreate ( CUcontext * pCtx , unsigned int flags , CUdevice device , VdpDevice vdpDevice , VdpGetProcAddress * vdpGetProcAddress ) ;
CUresult cuVDPAUCtxCreate_v2 ( CUcontext * pCtx , unsigned int flags , CUdevice device , VdpDevice vdpDevice , VdpGetProcAddress * vdpGetProcAddress ) ;
CUresult cuVDPAUGetDevice ( CUdevice * pDevice , VdpDevice vdpDevice , VdpGetProcAddress * vdpGetProcAddress ) ;
CUresult cuWaitExternalSemaphoresAsync_ptsz ( const CUexternalSemaphore * extSemArray , const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS * paramsArray , unsigned int numExtSems , CUstream stream ) ;
